name: cgInduction
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.1
  - attrs=21.4.0
  - bidict=0.21.2
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - contourpy=1.0.5
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dataclasses=0.8
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - fuzzywuzzy=0.18.0
  - giflib=5.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.42.0
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9e
  - jq=1.6
  - kiwisolver=1.4.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.0.3
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markdown=3.3.4
  - matplotlib-base=3.6.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.1.0
  - munkres=1.1.4
  - ncurses=6.3
  - nltk=3.7
  - numexpr=2.8.4
  - numpy=1.23.1
  - numpy-base=1.23.1
  - oauthlib=3.2.0
  - oniguruma=6.9.7.1
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.5.2
  - pillow=9.2.0
  - pip=22.1.2
  - protobuf=3.20.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-levenshtein=0.12.2
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2022.7
  - readline=8.1.2
  - regex=2022.7.9
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.12.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.39.2
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tqdm=4.64.0
  - treelib=1.6.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - urllib3=1.26.11
  - werkzeug=2.0.3
  - wheel=0.37.1
  - xz=5.2.5
  - yarl=1.6.3
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - metaphone==0.6
    - pronounceable==0.1.3
    - pyyaml==6.0
